KUstuProg: main.o
		g++ -std=c++11 -g -Wall main.o -o KUstuProg

main.o: main.cpp
		g++ -std=c++11 -g -Wall -c main.cpp

KUStudent.o: KUStudent.h
			g++ -std=c++11 -g -Wall -c KUStudent.h

clean:
		rm *.o KUstuProg
